default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  username: #######
  password: #######
  pool: 5

development:
  <<: *default
  database: qr_menu_development

test:
  <<: *default
  database: qr_menutest
