name: PR Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [main, master]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run standardrb
        run: bundle exec standardrb
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.6
        env:
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_test
        ports: [ "5432:5432" ]
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          POSTGRES_DB: ci_test
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: postgres
        run: |
          cp config/database.ci.yml config/database.yml
          cat config/database.yml
          bundle exec rails db:create db:migrate

      - name: Run tests
        env:
          PGHOST: localhost
          POSTGRES_DB: ci_test
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
          RAILS_ENV: test
        run: bundle exec rspec spec
